name: 'Weasel'
description: 'Static analysis for Solidity smart contracts'
author: 'slvDev'

branding:
  icon: 'shield'
  color: 'orange'

inputs:
  version:
    description: 'Weasel version to use (latest, nightly, or specific version like 0.5.0)'
    required: false
    default: 'latest'
  path:
    description: 'Path to analyze. If omitted, auto-detects from weasel.toml/foundry.toml/hardhat.config'
    required: false
    default: '.'
  min-severity:
    description: 'Minimum severity to report (High, Medium, Low, Gas, NC)'
    required: false
    default: 'Low'
  fail-on:
    description: 'Fail if findings at this severity or higher (High, Medium, Low, none)'
    required: false
    default: 'none'
  exclude:
    description: 'Paths to exclude (comma-separated)'
    required: false
    default: ''
  config:
    description: 'Path to weasel.toml config file'
    required: false
    default: ''
  sarif:
    description: 'Generate SARIF output for GitHub Code Scanning'
    required: false
    default: 'false'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'false'

outputs:
  findings:
    description: 'Number of findings'
    value: ${{ steps.weasel.outputs.findings }}
  report:
    description: 'Path to the report file'
    value: ${{ steps.weasel.outputs.report }}
  sarif-report:
    description: 'Path to the SARIF report file (if sarif=true)'
    value: ${{ steps.weasel.outputs.sarif_report }}

runs:
  using: 'composite'
  steps:
    - name: Resolve version
      id: resolve
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          # Get actual latest version for cache key (with fallback)
          RESOLVED=$(curl -fsSL -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/slvDev/weasel/releases/latest 2>/dev/null | \
            grep '"tag_name"' | sed -E 's/.*"v?([^"]+)".*/\1/' || echo "")
          if [ -z "$RESOLVED" ]; then
            echo "cache=false" >> "$GITHUB_OUTPUT"
          else
            echo "version=$RESOLVED" >> "$GITHUB_OUTPUT"
            echo "cache=true" >> "$GITHUB_OUTPUT"
          fi
        elif [ "$VERSION" = "nightly" ]; then
          echo "version=nightly" >> "$GITHUB_OUTPUT"
          echo "cache=false" >> "$GITHUB_OUTPUT"
        else
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "cache=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Cache Weasel
      id: cache
      if: steps.resolve.outputs.cache == 'true'
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ~/.weasel
        key: weasel-${{ runner.os }}-${{ runner.arch }}-${{ steps.resolve.outputs.version }}

    - name: Install Weasel
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/slvDev/weasel/main/weaselup/install | bash
        echo "$HOME/.weasel/bin" >> "$GITHUB_PATH"

        # Install specific version if requested
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "nightly" ]; then
          "$HOME/.weasel/bin/weaselup" --nightly
        elif [ "$VERSION" != "latest" ]; then
          "$HOME/.weasel/bin/weaselup" -v "$VERSION"
        fi

    - name: Add to PATH (cache hit)
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: echo "$HOME/.weasel/bin" >> "$GITHUB_PATH"

    - name: Run Weasel
      id: weasel
      shell: bash
      run: |
        # Build common args
        COMMON_ARGS="--min-severity ${{ inputs.min-severity }}"

        # Only add --scope if user explicitly set path (not default '.')
        # This allows Weasel to auto-detect from weasel.toml/foundry.toml/hardhat.config
        PATH_INPUT="${{ inputs.path }}"
        if [ "$PATH_INPUT" != "." ]; then
          COMMON_ARGS="--scope $PATH_INPUT $COMMON_ARGS"
        fi

        # Add excludes
        EXCLUDE_INPUT="${{ inputs.exclude }}"
        if [ -n "$EXCLUDE_INPUT" ]; then
          IFS=',' read -ra EXCLUDES <<< "$EXCLUDE_INPUT"
          for exc in "${EXCLUDES[@]}"; do
            COMMON_ARGS="$COMMON_ARGS --exclude $exc"
          done
        fi

        # Add config
        CONFIG_INPUT="${{ inputs.config }}"
        if [ -n "$CONFIG_INPUT" ]; then
          COMMON_ARGS="$COMMON_ARGS --config $CONFIG_INPUT"
        fi

        # Run JSON report
        weasel run $COMMON_ARGS --format json --output weasel-report
        JSON_EXIT=$?

        # Count findings
        if [ -f weasel-report.json ]; then
          FINDINGS=$(jq '.findings | length' weasel-report.json)
          echo "findings=$FINDINGS" >> "$GITHUB_OUTPUT"
          echo "report=weasel-report.json" >> "$GITHUB_OUTPUT"

          # Enhanced step summary with severity breakdown
          echo "### Weasel Analysis Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Severity | Count |" >> "$GITHUB_STEP_SUMMARY"
          echo "|----------|-------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| High | $(jq '[.findings[] | select(.severity=="High")] | length' weasel-report.json) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Medium | $(jq '[.findings[] | select(.severity=="Medium")] | length' weasel-report.json) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Low | $(jq '[.findings[] | select(.severity=="Low")] | length' weasel-report.json) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Gas | $(jq '[.findings[] | select(.severity=="Gas")] | length' weasel-report.json) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| NC | $(jq '[.findings[] | select(.severity=="NC")] | length' weasel-report.json) |" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "**Total: $FINDINGS**" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "findings=0" >> "$GITHUB_OUTPUT"
          echo "report=" >> "$GITHUB_OUTPUT"
          if [ $JSON_EXIT -ne 0 ]; then
            echo "::error::Weasel failed to run"
            exit $JSON_EXIT
          fi
        fi

        # Generate SARIF if requested
        if [ "${{ inputs.sarif }}" = "true" ]; then
          weasel run $COMMON_ARGS --format sarif --output weasel-report
          SARIF_EXIT=$?

          if [ -f weasel-report.sarif ]; then
            echo "sarif_report=weasel-report.sarif" >> "$GITHUB_OUTPUT"
          elif [ $SARIF_EXIT -ne 0 ]; then
            echo "::warning::SARIF generation failed"
          fi
        fi

    - name: Check fail condition
      shell: bash
      if: inputs.fail-on != 'none'
      run: |
        if [ ! -f weasel-report.json ]; then
          exit 0
        fi

        FAIL_ON="${{ inputs.fail-on }}"
        COUNT=0

        case $FAIL_ON in
          High)
            COUNT=$(jq '[.findings[] | select(.severity == "High")] | length' weasel-report.json)
            ;;
          Medium)
            COUNT=$(jq '[.findings[] | select(.severity == "High" or .severity == "Medium")] | length' weasel-report.json)
            ;;
          Low)
            COUNT=$(jq '[.findings[] | select(.severity == "High" or .severity == "Medium" or .severity == "Low")] | length' weasel-report.json)
            ;;
          *)
            echo "::warning::Unknown fail-on value: $FAIL_ON"
            COUNT=0
            ;;
        esac

        if [ "$COUNT" -gt 0 ]; then
          echo "::error::Weasel found $COUNT findings at $FAIL_ON severity or higher"
          exit 1
        fi

    - name: Upload SARIF to GitHub
      if: inputs.upload-sarif == 'true' && steps.weasel.outputs.sarif_report
      uses: github/codeql-action/upload-sarif@4bdb89f48054571735e3792627da6195c57459e2 # v3.31.10
      with:
        sarif_file: ${{ steps.weasel.outputs.sarif_report }}
        category: weasel
